#!/bin/bash

declare -a AppsArray
mapfile -t AppsArray < <(sed '/^$/d; /^#/d' ./app-list.txt)

sh="adb shell"
fdroid_link="https://f-droid.org/F-Droid.apk"
first_input="$1"
second_input="$2"

external_storage="$($sh find /storage -maxdepth 1 -name '*-*')"
internal_storage="/storage/emulated/0"

check_dependencies() {
    if [[ "$(command -v adb)" = "" ]]; then
        msg_dep_adb="\e[1;31m[?] \e[39mAndroid platform tools are not installed on your system."
        string_dependencies+="$msg_dep_adb\n"
    fi
    
    if [[ "$(command -v wget)" = "" ]]; then
        msg_dep_wget="\e[1;31m[?] \e[39mWget is not installed on your system."
        string_dependencies+="$msg_dep_wget\n"
    fi
    
    if [[ "$(command -v sed)" = "" ]]; then
        msg_dep_sed="\e[1;31m[?] \e[39mSed is not installed on your system."
        string_dependencies+="$msg_dep_sed\n"
    fi
    
    if [[ ! "$string_dependencies" = "" ]]; then
        printf '\n%b\n' "$string_dependencies"
        exit 127
    fi
}

# SETUP SECTION

setup_delete_apps() {
  for app in "${AppsArray[@]}"
  do
	printf '\n%b\n' "\e[1;33m[*] \e[0mDeleting \e[1m$app"

	if $sh pm uninstall --user 0 "$app" > /dev/null 2>&1
	then
	  printf '%b\n' "\e[1;32m[-] \e[0mDeleted \e[1m$app \e[0msuccessfully."
	else
	  printf '%b\n' "\e[1;31m[x] \e[0mCouldn't delete \e[1m$app."
	fi 
  done
}

setup_install_fdroid() {
  if [[ ! -f "./fdroid.apk" ]]; then
    if wget -O - $fdroid_link > ./fdroid.apk; then
      :
    else
      printf '%b\n\n' "\e[1;31m[x] \e[39mCouldn't download the F-Droid APK."
      exit 1
    fi
  fi

  printf '\n%b\n' "\e[1;33m[*] \e[39mInstalling F-Droid..."

  if adb install ./fdroid.apk > /dev/null 2>&1; then
    printf '%b\n\n' "\e[1;32m[+] \e[39mInstalled F-Droid successfully."
  else
    printf '%b\n\n' "\e[1;31m[x] \e[39mCouldn't install F-Droid."
    exit 1
  fi
}

# GENERAL SECTION

general_start_app() {
  if [[ "$second_input" = "" ]]; then
    printf '\n%b\n\n' "\e[1;31m[!] \e[39mNo input has given."
    printf '%b\n' "\e[0mTry these:"
    printf '%b\n' "\e[1m./debox -s com.android.vending\e[0m (starts play store)"
    printf '%b\n\n' "\e[1m./debox -s org.fdroid.fdroid\e[0m (starts f-droid)"
    exit 1
  elif $sh monkey -p "$second_input" -v 1
  then
    :
  else 
    printf '%b\n\n' "\e[1;31m[x] \e[39mCouldn't start the app."
    exit 1
  fi
}


general_send_input() {
  printf '\n%b\n' "\e[1;33m[*] \e[39mSending input to connected device."

  if [[ "$second_input" = "" ]]; then
    printf '%b\n\n' "\e[1;31m[!] \e[39mNo input has given."
  elif $sh input text "$second_input"
  then
    printf '%b\n\n' "\e[1;32m[+] \e[39mDone."
  else
    printf '%b\n\n' "\e[1;31m[x] \e[39mCouldn't send an input."
    exit 1
  fi
}

cleanup_empty_dirs() {
  for i in `seq 10`; do $sh find "$internal_storage" -type d -print -exec rmdir {} + 2>/dev/null ; done
  printf '%b\n\n' "\e[1;32m[+] \e[39mDeleted empty directories in internal storage."

  for i in `seq 10`; do $sh find "$external_storage" -type d -print -exec rmdir {} + 2>/dev/null ; done
  printf '%b\n\n' "\e[1;32m[+] \e[39mDeleted empty directories in external storage."
}

cleanup_delete_cache() {
  if $sh pm trim-caches 999G
  then
    printf '%b\n\n' "\e[1;32m[+] \e[39mDeleted all the cache."
  else
    printf '%b\n\n' "\e[1;31m[x] \e[39mCouldn't delete the cache."
    exit 1
  fi
}

print_usage() {
  printf '\n%b\n' "\e[1;32mDEBOX \e[39musage:\e[0m"
  printf '\n%b\n' "\e[1mSETUP COMMANDS\e[0m"
  printf '%b\n' "  ./debox {-a --automatic}                  user specific command, edit the script file"
  printf '%b\n' "  ./debox {-d --fdroid}                     install f-droid (with wget)"
  printf '%b\n' "  ./debox {-f --delete-apps}                delete the apps listed in app-list.txt"
  printf '\n%b\n' "\e[1mGENERAL COMMANDS\e[0m"
  printf '%b\n' "  ./debox {-s --strart} [com.package.name]  start a package"
  printf '%b\n' "  ./debox {-i --input} [text]               send a text input to the connected device"
  printf '%b\n' "  ./debox {-h --help}                       print this message"
  printf '\n%b\n' "\e[1mCLEANUP COMMANDS\e[0m"
  printf '%b\n' "  ./debox {-e --delete-empty-dirs}          delete empty directories from your internal and external storage"
  printf '%b\n\n' "  ./debox {-c --delete-cache}               delete caches of your all apps"
}


case $first_input in
  -a | --automatic) setup_delete_apps && setup_install_fdroid ;;
  -d | --fdroid) setup_install_fdroid ;;
  -f | --delete-apps) setup_delete_apps ;;
  -s | --start) general_start_app ;;
  -i | --input) general_send_input ;;
  -e | --delete-empty-dirs) cleanup_empty_dirs ;;
  *) print_usage
     exit 1 ;;
esac

