#!/bin/bash

declare -a AppsArray
mapfile -t AppsArray < <(sed '/^$/d; /^#/d' ./app-list.txt)

fdroid_link="https://f-droid.org/F-Droid.apk"
first_input="$1"
second_input="$2"

delete_apps() {
  for app in "${AppsArray[@]}"
  do
	printf '\n%b\n' "\e[1;33m[*] \e[0mDeleting \e[1m$app"

	if adb shell pm uninstall --user 0 "$app" > /dev/null 2>&1
	then
	  printf '%b\n' "\e[1;32m[-] \e[0mDeleted \e[1m$app \e[0msuccessfully."
        elif [[ "$(command -v adb)" = "" ]]; then
	  printf '%b\n\n' "\e[1;31m[?] \e[39mAndroid platform tools are not installed on your system."
	  exit 127
	else
	  printf '%b\n' "\e[1;31m[x] \e[0mCouldn't delete \e[1m$app."
	fi 
  done
}

install_fdroid() {
  if [[ ! -f "./fdroid.apk" ]]; then
    if wget -O - $fdroid_link > ./fdroid.apk; then
      :
    elif [[ "$(command -v wget)" = "" ]]; then
      printf '%b\n\n' "\e[1;31m[?] \e[39mWget is not installed on your system."
      exit 127
    else
      printf '%b\n\n' "\e[1;31m[x] \e[39mCouldn't download the F-Droid APK."
      exit 1
    fi
  fi

  printf '\n%b\n' "\e[1;33m[*] \e[39mInstalling F-Droid..."

  if adb install ./fdroid.apk > /dev/null 2>&1; then
    printf '%b\n\n' "\e[1;32m[+] \e[39mInstalled F-Droid successfully."
  elif [[ "$(command -v adb)" = "" ]]; then
    printf '%b\n\n' "\e[1;31m[?] \e[39mAndroid platform tools are not installed on your system."
    exit 127
  else
    printf '%b\n\n' "\e[1;31m[x] \e[39mCouldn't install F-Droid."
    exit 1
  fi
}

send_input() {
  printf '\n%b\n' "\e[1;33m[*] \e[39mSending input to connected device."

  if [[ "$second_input" = "" ]]; then
    printf '%b\n\n' "\e[1;31m[!] \e[39mNo input has given."
  elif adb shell input text "$second_input"
  then
    printf '%b\n\n' "\e[1;32m[+] \e[39mDone."
  elif [[ "$(command -v adb)" = "" ]]; then
    printf '%b\n\n' "\e[1;31m[?] \e[39mAndroid platform tools are not installed on your system."
    exit 127
  else
    printf '%b\n\n' "\e[1;31m[x] \e[39mCouldn't send an input."
    exit 1
  fi
}

start_app() {
  if [[ "$second_input" = "" ]]; then
    printf '\n%b\n\n' "\e[1;31m[!] \e[39mNo input has given."
    printf '%b\n' "\e[0mTry these:"
    printf '%b\n' "\e[1m./debox -s com.android.vending\e[0m (starts play store)"
    printf '%b\n\n' "\e[1m./debox -s org.fdroid.fdroid\e[0m (starts f-droid)"
    exit 1
  elif adb shell monkey -p "$second_input" -v 1
  then
    :
  elif [[ "$(command -v adb)" = "" ]]; then
    printf '%b\n\n' "\e[1;31m[?] \e[39mAndroid platform tools are not installed on your system."
    exit 127
  fi
}

print_usage() {
  printf '\n%b\n' "\e[1;32mDEBOX \e[39musage:\e[0m"
  printf '%b\n' "  ./debox {-a --automatic}                  user specific command, edit the script file"
  printf '%b\n' "  ./debox {-d --fdroid}                     install f-droid (with wget)"
  printf '%b\n' "  ./debox {-f --delete-apps}                delete the apps listed in app-list.txt"
  printf '%b\n' "  ./debox {-s --strart} [com.package.name]  start a package"
  printf '%b\n' "  ./debox {-i --input} [text]               send a text input to the connected device"
  printf '%b\n\n' "  ./debox {-h --help}                       print this message"
}

case $first_input in
  -a | --automatic) delete_apps && install_fdroid ;;
  -d | --fdroid) install_fdroid ;;
  -f | --delete-apps) delete_apps ;;
  -s | --start) start_app ;;
  -i | --input) send_input ;;
  *) print_usage
     exit 1 ;;
esac
